---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-errors: true
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: 'geerlingguy/docker-ubuntu1804-ansible:latest'
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
